# Generated by Django 4.1.7 on 2023-02-18 12:13

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['question'], 'verbose_name': 'Вопрос-Ответ'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='text',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Вопрос'),
        ),
    ]
