# Generated by Django 4.1.7 on 2023-02-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_faq_options_remove_faq_text_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['question'], 'verbose_name': 'Вопрос-Ответ', 'verbose_name_plural': 'Вопросы-Ответы'},
        ),
    ]
