# Generated by Django 4.1.7 on 2023-02-18 09:58

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('call_day', models.IntegerField(default=7, verbose_name='Через сколько дней сработает')),
                ('call_time', models.TimeField(verbose_name='В какое время сработает')),
                ('rols', models.CharField(choices=[('NC', 'Стажёр'), ('HR', 'HR'), ('DIR', 'Руководитель')], default='NC', max_length=10, verbose_name='Роль сотрудника')),
            ],
            options={
                'verbose_name': 'Уведомления',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_datetime', models.DateTimeField(verbose_name='Дата отправки')),
                ('send_status', models.BooleanField(default=True, verbose_name='Статус отправки')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='')),
            ],
        ),
    ]
