# Generated by Django 4.1.7 on 2023-02-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='call_day',
            field=models.IntegerField(default=7, verbose_name='Через сколько дней после регистрации пользователя сработает'),
        ),
    ]
