# Generated by Django 4.1.7 on 2023-02-18 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отдел',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rols', models.CharField(choices=[('NC', 'Стажёр'), ('HR', 'HR'), ('DIR', 'Руководитель')], default='NC', max_length=10)),
                ('phone', models.CharField(default='-', max_length=20)),
                ('telegram_id', models.CharField(default='-', max_length=50)),
                ('birthday', models.DateField(null=True, verbose_name='День рождение')),
                ('start_work', models.DateField(null=True, verbose_name='Старт работы в компании испытательного срока')),
                ('end_probation', models.DateField(null=True, verbose_name='Окончание испытательного срока')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='Отдел')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
