# Generated by Django 4.1.4 on 2023-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_id',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
