# Generated by Django 4.1.7 on 2023-02-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/profile/photo/', verbose_name='Фото'),
        ),
    ]
