# Generated by Django 4.1.7 on 2023-02-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_phone_alter_profile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True, verbose_name='День рождение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_probation',
            field=models.DateField(null=True, verbose_name='Окончание испытательного срока'),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_work',
            field=models.DateField(null=True, verbose_name='Старт работы в компании испытательного срока'),
        ),
    ]
