# Generated by Django 4.1.7 on 2023-02-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
    ]
