# Generated by Django 4.1.7 on 2023-02-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_photo'),
        ('users', '0003_profile_birthday_profile_end_probation_and_more'),
    ]

    operations = [
    ]
