# Generated by Django 4.1.7 on 2023-02-18 12:02

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='send_email_notification',
            field=models.BooleanField(default=False, verbose_name='Отправить на Email уведомление?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='send_telegram_notification',
            field=models.BooleanField(default=False, verbose_name='Отправить на TG уведомление?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
