# Generated by Django 4.1.7 on 2023-02-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_advertisement_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title'], 'verbose_name': 'Новости'},
        ),
    ]
