# Generated by Django 4.1.7 on 2023-02-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
