# Generated by Django 4.1.7 on 2023-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_advertisement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(null=True, upload_to='ads/photo', verbose_name='Картинка'),
        ),
    ]
