# Generated by Django 4.1.7 on 2023-02-18 06:18

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guideAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('bigBox', models.BooleanField(default=True, verbose_name='Сделать поле основным?')),
                ('required', models.BooleanField(default=True, verbose_name='Необходимый чек поинт?')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department')),
            ],
            options={
                'verbose_name': 'Карта',
                'ordering': ['department', 'order_count'],
            },
        ),
    ]
