# Generated by Django 4.1.4 on 2023-02-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadMaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideaction',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
