# Generated by Django 4.1.7 on 2023-02-18 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadMaps', '0002_alter_guideaction_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='guideActionCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Карта',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='guideaction',
            options={'ordering': ['category', 'order_count'], 'verbose_name': 'Карта'},
        ),
        migrations.AlterField(
            model_name='guideaction',
            name='order_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='guideaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadMaps.guideactioncategoria'),
        ),
    ]
