# Generated by Django 4.1.7 on 2023-02-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_phone_alter_profile_photo_and_more'),
        ('roadMaps', '0002_alter_guideaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserguideAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('guideAction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guideAction_users', to='roadMaps.guideaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_guideActions', to='users.profile')),
            ],
            options={
                'unique_together': {('user', 'guideAction')},
            },
        ),
    ]
