<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-02-18 19:38

from django.db import migrations
import django_ckeditor_5.fields
=======
# Generated by Django 4.1.7 on 2023-02-18 18:38

from django.db import migrations
>>>>>>> 70ae5d04228cee04c59284e277a811599965ad54


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_userachievementprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievementprogress',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='userachievementprogress',
            name='task_count',
        ),
<<<<<<< HEAD
        migrations.AlterField(
            model_name='achievement',
            name='conditions',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
=======
>>>>>>> 70ae5d04228cee04c59284e277a811599965ad54
    ]
