# Generated by Django 4.1.7 on 2023-02-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_userachievementprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userachievementprogress',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='userachievementprogress',
            name='task_count',
        ),
    ]
