# Generated by Django 4.1.7 on 2023-02-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_manager'),
        ('achievements', '0004_remove_userachievementprogress_points_earned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='users.profile'),
        ),
        migrations.DeleteModel(
            name='UserAchievementProgress',
        ),
    ]
