# Generated by Django 4.1.7 on 2023-02-18 20:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_alter_userachievement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='conditions',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание'),
        ),
    ]
