# Generated by Django 4.1.7 on 2023-02-18 10:55

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_to_task_comments_task_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
