# Generated by Django 4.1.7 on 2023-02-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_phone_alter_profile_photo_and_more'),
        ('knowledgebase', '0002_category_knowledgebase_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['title'], 'verbose_name': 'База знаний', 'verbose_name_plural': 'База знаний'},
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionList', to='users.department', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='knowledgebase/', verbose_name='Загрузить файл'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
