# Generated by Django 4.1.7 on 2023-02-19 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_phone_alter_profile_photo_and_more'),
        ('knowledgebase', '0003_alter_knowledgebase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledgebase', to='users.department', verbose_name='Категория'),
        ),
    ]
