# Generated by Django 4.1.7 on 2023-02-19 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_department'),
        ('knowledgebase', '0005_knowledgebase_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created', to='users.profile', verbose_name='Кем создано?'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
